version: "2"

volumes:
  kafka_data:
    driver: local

networks:
  bill-sentiment-network:
    driver: bridge

services:
  kafka-client-base: &base
    image: kafka-client-base
    build: ./
    networks:
      - bill-sentiment-network

  bill-retriever:
    image: bill-retriever
    build: ./bill_retriever
    depends_on:
      kafka-client-base:
        condition: service_completed_successfully
    networks:
      - bill-sentiment-network
      
  analyzer-textblob:
    image: analyzer-textblob
    build: ./analyzer_textblob
    depends_on:
      kafka-client-base:
        condition: service_completed_successfully
    networks:
      - bill-sentiment-network

  analyzer-vader:
    image: analyzer-vader
    build: ./analyzer_vader
    depends_on:
      kafka-client-base:
        condition: service_completed_successfully
    networks:
      - bill-sentiment-network

  kafka:
    image: docker.io/bitnami/kafka:3.5
    ports:
      - "9094:9094"
    volumes:
      - "kafka_data:/bitnami"
    networks:
      - bill-sentiment-network
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners   
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
