version: "2"

volumes:
  kafka_data:
    driver: local

networks:
  kafka-network:
    driver: bridge
  neo4j-network:
    driver: bridge

services:
  kafka-client-base: &base
    image: kafka-client-base
    build: ./

  bill-retriever:
    image: bill-retriever
    build: ./bill_retriever
    depends_on:
      kafka-client-base:
        condition: service_completed_successfully
    networks:
      - kafka-network
      
  analyzer-textblob:
    image: analyzer-textblob
    build: ./analyzer_textblob
    depends_on:
      kafka-client-base:
        condition: service_completed_successfully
      kafka:
        condition: service_healthy
    networks:
      - kafka-network

  analyzer-vader:
    image: analyzer-vader
    build: ./analyzer_vader
    depends_on:
      kafka-client-base:
        condition: service_completed_successfully
      kafka:
        condition: service_healthy
    networks:
      - kafka-network

  sentiment-aggregator:
    image: sentiment-aggregator
    build: ./sentiment_aggregator
    depends_on:
      kafka-client-base:
        condition: service_completed_successfully
      kafka:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    networks:
      - kafka-network
      - neo4j-network

  kafka:
    image: docker.io/bitnami/kafka:3.5
    ports:
      - "9094:9094"
    volumes:
      - "kafka_data:/bitnami"
    networks:
      - kafka-network
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners   
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --topic bill.raw --describe"]
      interval: 2s
      timeout: 2s
      retries: 15

  neo4j:
    image: docker.io/bitnami/neo4j:latest
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    networks:
      - neo4j-network
    healthcheck:
      test: [ "CMD", "/opt/bitnami/neo4j/bin/neo4j", "status" ]
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
